# Immich Stack - Test environment overrides
# Remaps ports (+10000 offset), uses test-prefixed volumes and networks

services:

  immich_machine_learning:
    container_name: "test_immich_machine_learning"
    networks: !override
      - "test_immich_default"
    volumes: !override
      - "test_immich_immich-ml-model-cache:/cache"

  immich_postgres:
    container_name: "test_immich_postgres"
    networks: !override
      - "test_immich_default"
    volumes: !override
      - "/home/koonan/immich-app/postgres-test:/var/lib/postgresql/data"

  immich_redis:
    container_name: "test_immich_redis"
    networks: !override
      - "test_immich_default"
    volumes: !override
      - "test_eeba826780300f3d846b69ccaecc2f70dc9dd09cdb8ce35b3eb4462d5ee3b122:/data"

  immich_server:
    container_name: "test_immich_server"
    networks: !override
      - "test_immich_default"
      - "test_traefik_default"
    ports: !override
      - "12283:2283/tcp"
    volumes: !override
      - "/data3/immich_data:/data"
      - "/etc/localtime:/etc/localtime:ro"

networks:

  immich_default:
    name: "immich_default_unused"

  traefik_default:
    name: "traefik_default_unused"

  test_immich_default:
    name: "test_immich_default"

  test_traefik_default:
    external: true
    name: "test_traefik_default"

volumes:

  eeba826780300f3d846b69ccaecc2f70dc9dd09cdb8ce35b3eb4462d5ee3b122:
    name: "eeba826780300f3d846b69ccaecc2f70dc9dd09cdb8ce35b3eb4462d5ee3b122_unused"

  immich_immich-ml-model-cache:
    name: "immich_immich-ml-model-cache_unused"

  test_eeba826780300f3d846b69ccaecc2f70dc9dd09cdb8ce35b3eb4462d5ee3b122:
    name: "test_eeba826780300f3d846b69ccaecc2f70dc9dd09cdb8ce35b3eb4462d5ee3b122"

  test_immich_immich-ml-model-cache:
    name: "test_immich_immich-ml-model-cache"
