# Docker Compose Configuration for Nova Self-Hosted Services
# Requires .env file in the same directory
# See .env.example for required environment variables
#
# DO NOT commit secrets to this file - use .env instead

networks:
  backrest_default:
    external: true
    name: "backrest_default"
  dockge_default:
    external: true
    name: "dockge_default"
  duplicati_default:
    external: true
    name: "duplicati_default"
  immich_default:
    external: true
    name: "immich_default"
  media:
    external: true
    name: "media"
  traefik_default:
    external: true
    name: "traefik_default"
  wud_default:
    external: true
    name: "wud_default"
  zwave_zwave:
    external: true
    name: "zwave_zwave"

services:

  backrest:

    command:
      - "/backrest"

    container_name: "backrest"

    entrypoint:
      - "/sbin/tini"
      - "--"
      - "/docker-entrypoint"

    environment:
      - "XDG_CACHE_HOME=/cache"
      - "TZ=America/Denver"
      - "BACKREST_DATA=/data"
      - "BACKREST_CONFIG=/config/config.json"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

    hostname: "backrest"

    image: "garethgeorge/backrest:latest"

    ipc: "private"

    labels:
      com.docker.compose.config-hash: "7a33fca0ca9f8d7b23cca298a8018effe3ba704718d8b3a792e7b91447fc1965"
      com.docker.compose.container-number: "1"
      com.docker.compose.depends_on: ""
      com.docker.compose.image: "sha256:e6721638ead42f61d047a13728d3c5c55b931041f807d3b85012d6d6f0f97356"
      com.docker.compose.oneoff: "False"
      com.docker.compose.project: "backrest"
      com.docker.compose.project.config_files: "/opt/stacks/backrest/compose.yaml"
      com.docker.compose.project.working_dir: "/opt/stacks/backrest"
      com.docker.compose.service: "backrest"
      com.docker.compose.version: "2.34.0"
      org.opencontainers.image.source: "https://github.com/garethgeorge/backrest"

    logging:
      driver: "json-file"
      options: {}

    networks:
      - "backrest_default"

    ports:
      - "9898:9898/tcp"

    restart: "unless-stopped"

    volumes:
      - "/data1:/hd1:ro"
      - "/data2:/hd2:ro"
      - "/data3:/hd3:ro"
      - "/home/koonan:/home:ro"
      - "/var/lib/docker/volumes:/volumes:ro"
      - "backrest_backrest_cache:/cache"
      - "backrest_backrest_config:/config"
      - "backrest_backrest_data:/data"

    working_dir: "/"

  bazarr:

    cap_drop:
      - "AUDIT_CONTROL"
      - "BLOCK_SUSPEND"
      - "DAC_READ_SEARCH"
      - "IPC_LOCK"
      - "IPC_OWNER"
      - "LEASE"
      - "LINUX_IMMUTABLE"
      - "MAC_ADMIN"
      - "MAC_OVERRIDE"
      - "NET_ADMIN"
      - "NET_BROADCAST"
      - "SYSLOG"
      - "SYS_ADMIN"
      - "SYS_BOOT"
      - "SYS_MODULE"
      - "SYS_NICE"
      - "SYS_PACCT"
      - "SYS_PTRACE"
      - "SYS_RAWIO"
      - "SYS_RESOURCE"
      - "SYS_TIME"
      - "SYS_TTY_CONFIG"
      - "WAKE_ALARM"

    container_name: "bazarr"

    entrypoint:
      - "/init"

    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=America/Chicago"
      - "PS1=$$(whoami)@$$(hostname):$$(pwd)\\$$"
      - "PATH=/lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "HOME=/root"
      - "TERM=xterm"
      - "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0"
      - "S6_VERBOSITY=1"
      - "S6_STAGE2_HOOK=/docker-mods"
      - "VIRTUAL_ENV=/lsiopy"
      - "LSIO_FIRST_PARTY=true"

    hostname: "f43384759f4f"

    image: "lscr.io/linuxserver/bazarr:latest"

    ipc: "private"

    labels:
      build_version: "Linuxserver.io version:- v1.5.3-ls324 Build-date:- 2025-10-28T21:30:03+00:00"
      maintainer: "chbmb"
      org.opencontainers.image.authors: "linuxserver.io"
      org.opencontainers.image.created: "2025-10-28T21:30:03+00:00"
      org.opencontainers.image.description: "[Bazarr](https://www.bazarr.media/) is a companion application\
        \ to Sonarr and Radarr. It can manage and download subtitles based on your requirements. You define\
        \ your preferences by TV show or movie and Bazarr takes care of everything for you."
      org.opencontainers.image.documentation: "https://docs.linuxserver.io/images/docker-bazarr"
      org.opencontainers.image.licenses: "GPL-3.0-only"
      org.opencontainers.image.ref.name: "bc19d74ce1ede34f9a96abed00d92f6e120f5b8d"
      org.opencontainers.image.revision: "bc19d74ce1ede34f9a96abed00d92f6e120f5b8d"
      org.opencontainers.image.source: "https://github.com/linuxserver/docker-bazarr"
      org.opencontainers.image.title: "Bazarr"
      org.opencontainers.image.url: "https://github.com/linuxserver/docker-bazarr/packages"
      org.opencontainers.image.vendor: "linuxserver.io"
      org.opencontainers.image.version: "v1.5.3-ls324"

    logging:
      driver: "json-file"
      options: {}

    mac_address: "e6:c9:5a:23:1d:15"

    network_mode: "bridge"

    ports:
      - "6767:6767/tcp"

    restart: "unless-stopped"

    volumes:
      - "/data1/plex_data_1/_data/movies:/plex_movies_1"
      - "/data1/plex_data_1/_data/tv:/plex_tv_1"
      - "/data2/movies:/plex_movies_2"
      - "/data2/tv:/plex_tv_2"
      - "/data3/movies:/plex_movies_3"
      - "/data3/tv:/plex_tv_3"
      - "/opt/subcleaner:/opt/subcleaner"
      - "bazarr_config:/config"

    working_dir: "/"

  dockge-dockge-1:
    command:
      - "tsx"
      - "./backend/index.ts"
    container_name: "dockge-dockge-1"
    entrypoint:
      - "/usr/bin/dumb-init"
      - "--"
    environment:
      - "DOCKGE_STACKS_DIR=/opt/stacks"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "NODE_VERSION=22.14.0"
      - "YARN_VERSION=1.22.22"
      - "UV_USE_IO_URING=0"
    hostname: "991d256607d3"
    image: "louislam/dockge:1"
    ipc: "private"
    labels:
      com.docker.compose.config-hash: "3f050a39e79270d9c2d6af4bb70ec1687282588958b84d68d2191911ad605707"
      com.docker.compose.container-number: "1"
      com.docker.compose.depends_on: ""
      com.docker.compose.image: "sha256:e85d511b2a8b883da8a1ac2fde39ecddacdc011734e9f89a14b7798d82d5a0d3"
      com.docker.compose.oneoff: "False"
      com.docker.compose.project: "dockge"
      com.docker.compose.project.config_files: "/opt/dockge/compose.yaml"
      com.docker.compose.project.working_dir: "/opt/dockge"
      com.docker.compose.service: "dockge"
      com.docker.compose.version: "2.35.1"
    logging:
      driver: "json-file"
      options: {}
    networks:
      - "dockge_default"
    ports:
      - "5001:5001/tcp"
    restart: "unless-stopped"
    volumes:
      - "/opt/dockge/data:/app/data"
      - "/opt/stacks:/opt/stacks"
      - "/var/run/docker.sock:/var/run/docker.sock"
    working_dir: "/app"

  duckdns:

    container_name: "duckdns"

    entrypoint:
      - "/init"

    environment:
      - "SUBDOMAINS=firefly-koonan"
      - "TOKEN=${DUCKDNS_TOKEN}"
      - "PATH=/lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "PS1=$$(whoami)@$$(hostname):$$(pwd)\\$$ "
      - "HOME=/root"
      - "TERM=xterm"
      - "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0"
      - "S6_VERBOSITY=1"
      - "S6_STAGE2_HOOK=/docker-mods"
      - "VIRTUAL_ENV=/lsiopy"
      - "LSIO_FIRST_PARTY=true"

    hostname: "8626b7da157a"

    image: "lscr.io/linuxserver/duckdns:latest"

    ipc: "private"

    labels:
      build_version: "Linuxserver.io version:- 95e5988b-ls68 Build-date:- 2025-10-27T04:22:01+00:00"
      maintainer: "aptalca"
      org.opencontainers.image.authors: "linuxserver.io"
      org.opencontainers.image.created: "2025-10-27T04:22:01+00:00"
      org.opencontainers.image.description: "[Duckdns](https://duckdns.org/) is a free service which will\
        \ point a DNS (sub domains of duckdns.org) to an IP of your choice. The service is completely\
        \ free, and doesn't require reactivation or forum posts to maintain its existence."
      org.opencontainers.image.documentation: "https://docs.linuxserver.io/images/docker-duckdns"
      org.opencontainers.image.licenses: "GPL-3.0-only"
      org.opencontainers.image.ref.name: "1da47edc1359ef22c2c1368f598e67679fd9de26"
      org.opencontainers.image.revision: "1da47edc1359ef22c2c1368f598e67679fd9de26"
      org.opencontainers.image.source: "https://github.com/linuxserver/docker-duckdns"
      org.opencontainers.image.title: "Duckdns"
      org.opencontainers.image.url: "https://github.com/linuxserver/docker-duckdns/packages"
      org.opencontainers.image.vendor: "linuxserver.io"
      org.opencontainers.image.version: "95e5988b-ls68"

    logging:
      driver: "json-file"
      options: {}

    mac_address: "7a:ef:8b:9f:d7:98"

    network_mode: "bridge"

    restart: "unless-stopped"

    working_dir: "/"

  duplicati:

    container_name: "duplicati"

    entrypoint:
      - "/init"

    environment:
      - "SETTINGS_ENCRYPTION_KEY=${DUPLICATI_SETTINGS_ENCRYPTION_KEY}"
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=America/Denver"
      - "PATH=/lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "HOME=/config"
      - "LANGUAGE=en_US.UTF-8"
      - "LANG=en_US.UTF-8"
      - "TERM=xterm"
      - "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0"
      - "S6_VERBOSITY=1"
      - "S6_STAGE2_HOOK=/docker-mods"
      - "VIRTUAL_ENV=/lsiopy"
      - "LSIO_FIRST_PARTY=true"
      - "TMPDIR=/run/duplicati-temp"
      - "DUPLICATI__REQUIRE_DB_ENCRYPTION_KEY=true"
      - "DUPLICATI__SERVER_DATAFOLDER=/config"
      - "DUPLICATI__WEBSERVICE_PORT=8200"
      - "DUPLICATI__WEBSERVICE_INTERFACE=any"
      - "DUPLICATI__WEBSERVICE_ALLOWED_HOSTNAMES=*"

    hostname: "de744074a1d1"

    image: "lscr.io/linuxserver/duplicati:latest"

    ipc: "private"

    labels:
      build_version: "Linuxserver.io version:- v2.2.0.0_stable_2025-10-23-ls264 Build-date:- 2025-11-01T04:01:03+00:00"
      com.docker.compose.config-hash: "83fbb7229ef80109c2aa55353d55d28228cedd2089ecf620ac0fe3d4b19b3b22"
      com.docker.compose.container-number: "1"
      com.docker.compose.depends_on: ""
      com.docker.compose.image: "sha256:a4ae9c4176b85f16039901910e7114dcba9e9a0cee27406edc5045901a2d753c"
      com.docker.compose.oneoff: "False"
      com.docker.compose.project: "duplicati"
      com.docker.compose.project.config_files: "/home/koonan/duplicati/docker-compose.yaml"
      com.docker.compose.project.working_dir: "/home/koonan/duplicati"
      com.docker.compose.replace: "8d68316860b702e89e3d605a1a2790d98da195517323e2993b6d6311bf0a5162"
      com.docker.compose.service: "duplicati"
      com.docker.compose.version: "2.35.1"
      maintainer: "aptalca"
      org.opencontainers.image.authors: "linuxserver.io"
      org.opencontainers.image.created: "2025-11-01T04:01:03+00:00"
      org.opencontainers.image.description: "[Duplicati](https://www.duplicati.com/) is a backup client\
        \ that securely stores encrypted, incremental, compressed backups on local storage, cloud storage\
        \ services and remote file servers. It works with standard protocols like FTP, SSH, WebDAV as\
        \ well as popular services like Microsoft OneDrive, Amazon S3, Google Drive, box.com, Mega, B2,\
        \ and many others."
      org.opencontainers.image.documentation: "https://docs.linuxserver.io/images/docker-duplicati"
      org.opencontainers.image.licenses: "GPL-3.0-only"
      org.opencontainers.image.ref.name: "b52d33d4310bc1111f3384483fd6235ae9381f8e"
      org.opencontainers.image.revision: "b52d33d4310bc1111f3384483fd6235ae9381f8e"
      org.opencontainers.image.source: "https://github.com/linuxserver/docker-duplicati"
      org.opencontainers.image.title: "Duplicati"
      org.opencontainers.image.url: "https://github.com/linuxserver/docker-duplicati/packages"
      org.opencontainers.image.vendor: "linuxserver.io"
      org.opencontainers.image.version: "v2.2.0.0_stable_2025-10-23-ls264"

    logging:
      driver: "json-file"
      options: {}

    networks:
      - "duplicati_default"

    ports:
      - "8200:8200/tcp"

    restart: "unless-stopped"

    volumes:
      - "/backups:/backups"
      - "/docker/duplicati/config:/config"
      - "/var/lib/docker/volumes:/source:ro"

    working_dir: "/"

  homeassistant:

    cap_drop:
      - "CAP_AUDIT_CONTROL"
      - "CAP_BLOCK_SUSPEND"
      - "CAP_DAC_READ_SEARCH"
      - "CAP_IPC_LOCK"
      - "CAP_IPC_OWNER"
      - "CAP_LEASE"
      - "CAP_LINUX_IMMUTABLE"
      - "CAP_MAC_ADMIN"
      - "CAP_MAC_OVERRIDE"
      - "CAP_NET_ADMIN"
      - "CAP_NET_BROADCAST"
      - "CAP_SYSLOG"
      - "CAP_SYS_ADMIN"
      - "CAP_SYS_BOOT"
      - "CAP_SYS_MODULE"
      - "CAP_SYS_NICE"
      - "CAP_SYS_PACCT"
      - "CAP_SYS_PTRACE"
      - "CAP_SYS_RAWIO"
      - "CAP_SYS_RESOURCE"
      - "CAP_SYS_TIME"
      - "CAP_SYS_TTY_CONFIG"
      - "CAP_WAKE_ALARM"

    container_name: "homeassistant"

    entrypoint:
      - "/init"

    environment:
      - "LANG=C.UTF-8"
      - "PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "S6_BEHAVIOUR_IF_STAGE2_FAILS=2"
      - "S6_CMD_WAIT_FOR_SERVICES=1"
      - "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0"
      - "S6_SERVICES_GRACETIME=220000"
      - "S6_SERVICES_READYTIME=50"
      - "TZ=America/Chicago"
      - "WHEELS_LINKS=https://wheels.home-assistant.io/alpine-3.14/amd64/"
      - "UV_EXTRA_INDEX_URL=https://wheels.home-assistant.io/musllinux-index/"
      - "UV_SYSTEM_PYTHON=true"
      - "UV_NO_CACHE=true"

    hostname: "serenity"

    image: "ghcr.io/home-assistant/home-assistant:stable"

    ipc: "private"

    labels:
      io.hass.arch: "amd64"
      io.hass.base.arch: "amd64"
      io.hass.base.image: "homeassistant/amd64-base:3.14"
      io.hass.base.name: "python"
      io.hass.base.version: "2021.09.1"
      io.hass.type: "core"
      io.hass.version: "2021.10.6"
      org.opencontainers.image.authors: "The Home Assistant Authors"
      org.opencontainers.image.created: "2021-10-18 06:34:53+00:00"
      org.opencontainers.image.description: "Open-source home automation platform running on Python 3"
      org.opencontainers.image.documentation: "https://www.home-assistant.io/docs/"
      org.opencontainers.image.licenses: "Apache License 2.0"
      org.opencontainers.image.source: "https://github.com/home-assistant/core"
      org.opencontainers.image.title: "Home Assistant"
      org.opencontainers.image.url: "https://www.home-assistant.io/"
      org.opencontainers.image.version: "2021.10.6"

    logging:
      driver: "json-file"
      options: {}

    network_mode: "host"

    privileged: true

    restart: "unless-stopped"

    security_opt:
      - "label=disable"

    volumes:
      - "ha_config:/config"

    working_dir: "/config"

  immich_machine_learning:

    command:
      - "python"
      - "-m"
      - "immich_ml"

    container_name: "immich_machine_learning"

    entrypoint:
      - "tini"
      - "--"

    environment:
      - "IMMICH_VERSION=release"
      - "DB_PASSWORD=${IMMICH_DB_PASSWORD}"
      - "DB_USERNAME=postgres"
      - "DB_DATABASE_NAME=immich"
      - "UPLOAD_LOCATION=/data3/immich_data"
      - "DB_DATA_LOCATION=./postgres"
      - "TZ=America/Denver"
      - "PATH=/opt/venv/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "LANG=C.UTF-8"
      - "GPG_KEY=A035C8C19219BA821ECEA86B64E628F8D684696D"
      - "PYTHON_VERSION=3.11.13"
      - "PYTHON_SHA256=8fb5f9fbc7609fa822cb31549884575db7fd9657cbffb89510b5d7975963a83a"
      - "LD_PRELOAD=/usr/lib/libmimalloc.so.2"
      - "MACHINE_LEARNING_MODEL_ARENA=false"
      - "TRANSFORMERS_CACHE=/cache"
      - "PYTHONDONTWRITEBYTECODE=1"
      - "PYTHONUNBUFFERED=1"
      - "PYTHONPATH=/usr/src"
      - "DEVICE=cpu"
      - "VIRTUAL_ENV=/opt/venv"
      - "MACHINE_LEARNING_CACHE_FOLDER=/cache"
      - "IMMICH_BUILD=19104095433"
      - "IMMICH_BUILD_URL=https://github.com/immich-app/immich/actions/runs/19104095433"
      - "IMMICH_BUILD_IMAGE=v2.2.3"
      - "IMMICH_BUILD_IMAGE_URL=https://github.com/immich-app/immich/pkgs/container/immich-machine-learning"
      - "IMMICH_REPOSITORY=immich-app/immich"
      - "IMMICH_REPOSITORY_URL=https://github.com/immich-app/immich"
      - "IMMICH_SOURCE_REF=v2.2.3"
      - "IMMICH_SOURCE_COMMIT=28eb1bc13cfd4642fe90fd8cf724ba7acf94f675"
      - "IMMICH_SOURCE_URL=https://github.com/immich-app/immich/commit/28eb1bc13cfd4642fe90fd8cf724ba7acf94f675"

    hostname: "2c80652fc6f9"

    image: "ghcr.io/immich-app/immich-machine-learning:release"

    ipc: "private"

    labels:
      com.docker.compose.config-hash: "92e3e77f2dd37337a729acf8afc4c4e4aaaa7f5470e4d61471cf5446410dcfea"
      com.docker.compose.container-number: "1"
      com.docker.compose.depends_on: ""
      com.docker.compose.image: "sha256:cbaddc4758c400262039a03eb39ad4d6a06faeb31ece46a6594701fc9529affc"
      com.docker.compose.oneoff: "False"
      com.docker.compose.project: "immich"
      com.docker.compose.project.config_files: "/home/koonan/immich-app/docker-compose.yml"
      com.docker.compose.project.working_dir: "/home/koonan/immich-app"
      com.docker.compose.service: "immich-machine-learning"
      com.docker.compose.version: "2.35.1"
      org.opencontainers.image.created: "2025-11-05T13:47:44.676Z"
      org.opencontainers.image.description: "High performance self-hosted photo and video management solution."
      org.opencontainers.image.licenses: "AGPL-3.0"
      org.opencontainers.image.revision: "28eb1bc13cfd4642fe90fd8cf724ba7acf94f675"
      org.opencontainers.image.source: "https://github.com/immich-app/immich"
      org.opencontainers.image.title: "immich"
      org.opencontainers.image.url: "https://github.com/immich-app/immich"
      org.opencontainers.image.version: "v2.2.3"

    logging:
      driver: "json-file"
      options: {}

    networks:
      - "immich_default"

    restart: "always"

    volumes:
      - "immich_immich-ml-model-cache:/cache"

    working_dir: "/usr/src"

  immich_postgres:

    command:
      - "postgres"
      - "-c"
      - "config_file=/etc/postgresql/postgresql.conf"

    container_name: "immich_postgres"

    entrypoint:
      - "/usr/local/bin/immich-docker-entrypoint.sh"

    environment:
      - "POSTGRES_INITDB_ARGS=--data-checksums"
      - "POSTGRES_PASSWORD=${IMMICH_DB_PASSWORD}"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_DB=immich"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/postgresql/14/bin"
      - "GOSU_VERSION=1.17"
      - "LANG=en_US.utf8"
      - "PG_MAJOR=14"
      - "PG_VERSION=14.18-1.pgdg120+1"
      - "PGDATA=/var/lib/postgresql/data"
      - "DB_STORAGE_TYPE=SSD"

    expose:
      - "5432/tcp"

    hostname: "6649e79b630e"

    image: "ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:32324a2f41df5de9efe1af166b7008c3f55646f8d0e00d9550c16c9822366b4a"

    ipc: "private"

    labels:
      com.docker.compose.config-hash: "ff35c289ecbec99e2d84d5db5a4cca70491c0ee181ab9109f4a768a0255d13eb"
      com.docker.compose.container-number: "1"
      com.docker.compose.depends_on: ""
      com.docker.compose.image: "sha256:86a9b06ef82525cd385caaa029b5fb21e8206ddf12a5441e66e9dec4348609c7"
      com.docker.compose.oneoff: "False"
      com.docker.compose.project: "immich"
      com.docker.compose.project.config_files: "/home/koonan/immich-app/docker-compose.yml"
      com.docker.compose.project.working_dir: "/home/koonan/immich-app"
      com.docker.compose.service: "database"
      com.docker.compose.version: "2.35.1"
      org.opencontainers.image.created: "2025-07-23T21:03:59.099Z"
      org.opencontainers.image.description: "Base images for Immich containers"
      org.opencontainers.image.licenses: "AGPL-3.0"
      org.opencontainers.image.revision: "ee806e819e922de0a2744cf61da90428b169dc4a"
      org.opencontainers.image.source: "https://github.com/immich-app/base-images"
      org.opencontainers.image.title: "base-images"
      org.opencontainers.image.url: "https://github.com/immich-app/base-images"
      org.opencontainers.image.version: "14-vectorchord0.4.3-pgvector0.8.0-pgvectors0.2.0"

    logging:
      driver: "json-file"
      options: {}

    networks:
      - "immich_default"

    restart: "always"

    volumes:
      - "/home/koonan/immich-app/postgres:/var/lib/postgresql/data"

  immich_redis:
    command:
      - "valkey-server"
    container_name: "immich_redis"
    entrypoint:
      - "docker-entrypoint.sh"
    environment:
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "VALKEY_VERSION=8.1.3"
    expose:
      - "6379/tcp"
    hostname: "1e78005ab8d5"
    image: "docker.io/valkey/valkey:8-bookworm@sha256:a137a2b60aca1a75130022d6bb96af423fefae4eb55faf395732db3544803280"
    ipc: "private"
    labels:
      com.docker.compose.config-hash: "2e187c8585a9a43c222d935ab5e5e99e955238cc6da0f75c39123093cc7fa6f8"
      com.docker.compose.container-number: "1"
      com.docker.compose.depends_on: ""
      com.docker.compose.image: "sha256:7cb874b6878d1a539328fa947200bfae55d8af78a3884209a99733eef7d0d970"
      com.docker.compose.oneoff: "False"
      com.docker.compose.project: "immich"
      com.docker.compose.project.config_files: "/home/koonan/immich-app/docker-compose.yml"
      com.docker.compose.project.working_dir: "/home/koonan/immich-app"
      com.docker.compose.service: "redis"
      com.docker.compose.version: "2.35.1"
    logging:
      driver: "json-file"
      options: {}
    networks:
      - "immich_default"
    restart: "always"
    volumes:
      - "eeba826780300f3d846b69ccaecc2f70dc9dd09cdb8ce35b3eb4462d5ee3b122:/data"
    working_dir: "/data"

  immich_server:

    command:
      - "start.sh"

    container_name: "immich_server"

    entrypoint:
      - "tini"
      - "--"
      - "/bin/bash"
      - "-c"

    environment:
      - "IMMICH_VERSION=release"
      - "DB_PASSWORD=${IMMICH_DB_PASSWORD}"
      - "DB_USERNAME=postgres"
      - "DB_DATABASE_NAME=immich"
      - "UPLOAD_LOCATION=/data3/immich_data"
      - "DB_DATA_LOCATION=./postgres"
      - "TZ=America/Denver"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/src/app/server/bin"
      - "NODE_VERSION=22.18.0"
      - "YARN_VERSION=1.22.22"
      - "DEBIAN_RELEASE=trixie"
      - "LD_LIBRARY_PATH=/usr/lib/jellyfin-ffmpeg/lib:/usr/lib/wsl/lib"
      - "NODE_ENV=production"
      - "NVIDIA_DRIVER_CAPABILITIES=all"
      - "NVIDIA_VISIBLE_DEVICES=all"
      - "IMMICH_BUILD=19104095433"
      - "IMMICH_BUILD_URL=https://github.com/immich-app/immich/actions/runs/19104095433"
      - "IMMICH_BUILD_IMAGE=v2.2.3"
      - "IMMICH_BUILD_IMAGE_URL=https://github.com/immich-app/immich/pkgs/container/immich-server"
      - "IMMICH_REPOSITORY=immich-app/immich"
      - "IMMICH_REPOSITORY_URL=https://github.com/immich-app/immich"
      - "IMMICH_SOURCE_REF=v2.2.3"
      - "IMMICH_SOURCE_COMMIT=28eb1bc13cfd4642fe90fd8cf724ba7acf94f675"
      - "IMMICH_SOURCE_URL=https://github.com/immich-app/immich/commit/28eb1bc13cfd4642fe90fd8cf724ba7acf94f675"

    hostname: "0dbb383705f9"

    image: "ghcr.io/immich-app/immich-server:release"

    ipc: "private"

    labels:
      com.docker.compose.config-hash: "1dfacdd8fab19e5a06b52ee6795891964104887a033df39de3cd3166403eec71"
      com.docker.compose.container-number: "1"
      com.docker.compose.depends_on: "redis:service_started:false,database:service_started:false"
      com.docker.compose.image: "sha256:f2d652a5104fa1533ba0b43012c802ce43b1f517ada456b8f8522cef29ff2fbd"
      com.docker.compose.oneoff: "False"
      com.docker.compose.project: "immich"
      com.docker.compose.project.config_files: "/home/koonan/immich-app/docker-compose.yml"
      com.docker.compose.project.working_dir: "/home/koonan/immich-app"
      com.docker.compose.service: "immich-server"
      com.docker.compose.version: "2.35.1"
      org.opencontainers.image.created: "2025-11-05T13:47:40.897Z"
      org.opencontainers.image.description: "High performance self-hosted photo and video management solution."
      org.opencontainers.image.licenses: "AGPL-3.0"
      org.opencontainers.image.revision: "28eb1bc13cfd4642fe90fd8cf724ba7acf94f675"
      org.opencontainers.image.source: "https://github.com/immich-app/immich"
      org.opencontainers.image.title: "immich"
      org.opencontainers.image.url: "https://github.com/immich-app/immich"
      org.opencontainers.image.version: "v2.2.3"

    logging:
      driver: "json-file"
      options: {}

    networks:
      - "immich_default"

    ports:
      - "2283:2283/tcp"

    restart: "always"

    volumes:
      - "/data3/immich_data:/data"
      - "/etc/localtime:/etc/localtime:ro"

    working_dir: "/usr/src/app"

  jackett:

    cap_drop:
      - "AUDIT_CONTROL"
      - "BLOCK_SUSPEND"
      - "DAC_READ_SEARCH"
      - "IPC_LOCK"
      - "IPC_OWNER"
      - "LEASE"
      - "LINUX_IMMUTABLE"
      - "MAC_ADMIN"
      - "MAC_OVERRIDE"
      - "NET_ADMIN"
      - "NET_BROADCAST"
      - "SYSLOG"
      - "SYS_ADMIN"
      - "SYS_BOOT"
      - "SYS_MODULE"
      - "SYS_NICE"
      - "SYS_PACCT"
      - "SYS_PTRACE"
      - "SYS_RAWIO"
      - "SYS_RESOURCE"
      - "SYS_TIME"
      - "SYS_TTY_CONFIG"
      - "WAKE_ALARM"

    container_name: "jackett"

    entrypoint:
      - "/init"

    environment:
      - "TZ=America/Chicago"
      - "AUTO_UPDATE=true"
      - "PUID=1000"
      - "PGID=1000"
      - "PATH=/lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "PS1=$$(whoami)@$$(hostname):$$(pwd)\\$$ "
      - "HOME=/root"
      - "TERM=xterm"
      - "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0"
      - "S6_VERBOSITY=1"
      - "S6_STAGE2_HOOK=/docker-mods"
      - "VIRTUAL_ENV=/lsiopy"
      - "LSIO_FIRST_PARTY=true"
      - "XDG_DATA_HOME=/config"
      - "XDG_CONFIG_HOME=/config"
      - "TMPDIR=/run/jackett-temp"

    hostname: "jackett"

    image: "lscr.io/linuxserver/jackett:latest"

    ipc: "private"

    labels:
      build_version: "Linuxserver.io version:- v0.18.896-ls47 Build-date:- 2021-10-04T07:22:52+02:00"
      maintainer: "thelamer"
      org.opencontainers.image.authors: "linuxserver.io"
      org.opencontainers.image.created: "2021-10-04T07:22:52+02:00"
      org.opencontainers.image.description: "[Jackett](https://github.com/Jackett/Jackett) works as a\
        \ proxy server: it translates queries from apps (Sonarr, SickRage, CouchPotato, Mylar, etc) into\
        \ tracker-site-specific http queries, parses the html response, then sends results back to the\
        \ requesting software. This allows for getting recent uploads (like RSS) and performing searches.\
        \ Jackett is a single repository of maintained indexer scraping & translation logic - removing\
        \ the burden from other apps."
      org.opencontainers.image.documentation: "https://docs.linuxserver.io/images/docker-jackett"
      org.opencontainers.image.licenses: "GPL-3.0-only"
      org.opencontainers.image.ref.name: "6d9f06e8e15bd5d03c82702cbb2a240c93c7159a"
      org.opencontainers.image.revision: "6d9f06e8e15bd5d03c82702cbb2a240c93c7159a"
      org.opencontainers.image.source: "https://github.com/linuxserver/docker-jackett"
      org.opencontainers.image.title: "Jackett"
      org.opencontainers.image.url: "https://github.com/linuxserver/docker-jackett/packages"
      org.opencontainers.image.vendor: "linuxserver.io"
      org.opencontainers.image.version: "v0.18.896-ls47"

    logging:
      driver: "json-file"
      options: {}

    networks:
      - "media"

    ports:
      - "9117:9117/tcp"

    restart: "unless-stopped"

    volumes:
      - "jackett_config:/config"
      - "jackett_download:/downloads"

    working_dir: "/"

  minecraft:

    cap_drop:
      - "AUDIT_CONTROL"
      - "BLOCK_SUSPEND"
      - "DAC_READ_SEARCH"
      - "IPC_LOCK"
      - "IPC_OWNER"
      - "LEASE"
      - "LINUX_IMMUTABLE"
      - "MAC_ADMIN"
      - "MAC_OVERRIDE"
      - "NET_ADMIN"
      - "NET_BROADCAST"
      - "SYSLOG"
      - "SYS_ADMIN"
      - "SYS_BOOT"
      - "SYS_MODULE"
      - "SYS_NICE"
      - "SYS_PACCT"
      - "SYS_PTRACE"
      - "SYS_RAWIO"
      - "SYS_RESOURCE"
      - "SYS_TIME"
      - "SYS_TTY_CONFIG"
      - "WAKE_ALARM"

    container_name: "minecraft"

    entrypoint:
      - "/start"

    environment:
      - "EULA=TRUE"
      - "PATH=/opt/java/openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "JAVA_HOME=/opt/java/openjdk"
      - "LANG=en_US.UTF-8"
      - "LANGUAGE=en_US:en"
      - "LC_ALL=en_US.UTF-8"
      - "JAVA_VERSION=jdk-21.0.5+11"
      - "TYPE=VANILLA"
      - "VERSION=LATEST"
      - "UID=1000"
      - "GID=1000"

    hostname: "adcfacfd63e3"

    image: "itzg/minecraft-server:latest"

    ipc: "private"

    labels:
      org.opencontainers.image.authors: "Geoff Bourne <itzgeoff@gmail.com>"
      org.opencontainers.image.created: "2024-12-14T21:22:25.728Z"
      org.opencontainers.image.description: "Docker image that provides a Minecraft Server that will automatically\
        \ download selected version at startup"
      org.opencontainers.image.licenses: "Apache-2.0"
      org.opencontainers.image.ref.name: "ubuntu"
      org.opencontainers.image.revision: "de19794a5fa90a7736d7fc461c1978d70516c129"
      org.opencontainers.image.source: "https://github.com/itzg/docker-minecraft-server"
      org.opencontainers.image.title: "docker-minecraft-server"
      org.opencontainers.image.url: "https://github.com/itzg/docker-minecraft-server"
      org.opencontainers.image.version: "java21"

    logging:
      driver: "json-file"
      options: {}

    network_mode: "bridge"

    ports:
      - "25565:25565/tcp"

    stdin_open: true

    tty: true

    volumes:
      - "minecraft_data:/data"

    working_dir: "/data"

  music-assistant-server:

    container_name: "music-assistant-server"

    entrypoint:
      - "/usr/local/bin/entrypoint.sh"
      - "--data-dir"
      - "/data"
      - "--cache-dir"
      - "/data/.cache"

    environment:
      - "LOG_LEVEL=info"
      - "PATH=/app/venv/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "GPG_KEY=7169605F62C751356D054A26A821E680E5FA6305"
      - "PYTHON_VERSION=3.13.11"
      - "PYTHON_SHA256=16ede7bb7cdbfa895d11b0642fa0e523f291e6487194d53cf6d3b338c3a17ea2"
      - "VIRTUAL_ENV=/app/venv"

    expose:
      - "8095/tcp"

    hostname: "nova"

    image: "ghcr.io/music-assistant/server:latest"

    ipc: "private"

    labels:
      com.docker.compose.config-hash: "5e5157352c304e9e3d253c2e00378cbc193a3a227071ae4a9f1849c1adaa5e60"
      com.docker.compose.container-number: "1"
      com.docker.compose.depends_on: ""
      com.docker.compose.image: "sha256:2d9e8e000490f14c40aeeb723bfa8c0b5da2c79412036493cd6749cd95772cf5"
      com.docker.compose.oneoff: "False"
      com.docker.compose.project: "music-assistant"
      com.docker.compose.project.config_files: "/home/koonan/music-assistant/docker-compose.yaml"
      com.docker.compose.project.working_dir: "/home/koonan/music-assistant"
      com.docker.compose.service: "music-assistant-server"
      com.docker.compose.version: "2.35.1"
      io.hass.description: "Music Assistant Server"
      io.hass.name: "Music Assistant Server"
      io.hass.platform: "linux/amd64"
      io.hass.type: "addon"
      io.hass.version: "2.7.6"
      org.opencontainers.image.authors: "The Music Assistant Team"
      org.opencontainers.image.description: "Music Assistant is a free, opensource Media library manager\
        \ that connects to your streaming services and a wide range of connected speakers. The server\
        \ is the beating heart, the core of Music Assistant and must run on an always-on device like a\
        \ Raspberry Pi, a NAS or an Intel NUC or alike."
      org.opencontainers.image.documentation: "https://music-assistant.io"
      org.opencontainers.image.licenses: "Apache License 2.0"
      org.opencontainers.image.source: "https://github.com/music-assistant/server"
      org.opencontainers.image.title: "Music Assistant Server"

    logging:
      driver: "json-file"
      options: {}

    network_mode: "host"

    restart: "unless-stopped"

    security_opt:
      - "apparmor:unconfined"

    volumes:
      - "/home/koonan/docker/music-assistant-server/data:/data"

    working_dir: "/app/venv"

  ombi:

    cap_drop:
      - "AUDIT_CONTROL"
      - "BLOCK_SUSPEND"
      - "DAC_READ_SEARCH"
      - "IPC_LOCK"
      - "IPC_OWNER"
      - "LEASE"
      - "LINUX_IMMUTABLE"
      - "MAC_ADMIN"
      - "MAC_OVERRIDE"
      - "NET_ADMIN"
      - "NET_BROADCAST"
      - "SYSLOG"
      - "SYS_ADMIN"
      - "SYS_BOOT"
      - "SYS_MODULE"
      - "SYS_NICE"
      - "SYS_PACCT"
      - "SYS_PTRACE"
      - "SYS_RAWIO"
      - "SYS_RESOURCE"
      - "SYS_TIME"
      - "SYS_TTY_CONFIG"
      - "WAKE_ALARM"

    container_name: "ombi"

    entrypoint:
      - "/init"

    environment:
      - "BASE_URL=/ombi"
      - "DEBIAN_FRONTEND=noninteractive"
      - "HOME=/config"
      - "LANG=en_US.UTF-8"
      - "LANGUAGE=en_US.UTF-8"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "PGID=1000"
      - "PUID=1000"
      - "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0"
      - "S6_STAGE2_HOOK=/docker-mods"
      - "S6_VERBOSITY=1"
      - "TERM=xterm"
      - "TZ=America/Chicago"

    hostname: "40bd9c6d4f40"

    image: "linuxserver/ombi:amd64-4.16.11"

    ipc: "private"

    labels:
      build_version: "Linuxserver.io version:- v4.0.1468-ls108 Build-date:- 2021-10-12T10:32:31+02:00"
      maintainer: "aptalca"
      org.opencontainers.image.authors: "linuxserver.io"
      org.opencontainers.image.created: "2021-10-12T10:32:31+02:00"
      org.opencontainers.image.description: "[Ombi](https://ombi.io) allows you to host your own Plex\
        \ Request and user management system.  If you are sharing your Plex server with other users, allow\
        \ them to request new content using an easy to manage interface!  Manage all your requests for\
        \ Movies and TV with ease, leave notes for the user and get notification when a user requests\
        \ something.  Allow your users to post issues against their requests so you know there is a problem\
        \ with the audio etc.  Even automatically send them weekly newsletters of new content that has\
        \ been added to your Plex server!"
      org.opencontainers.image.documentation: "https://docs.linuxserver.io/images/docker-ombi"
      org.opencontainers.image.licenses: "GPL-3.0-only"
      org.opencontainers.image.ref.name: "8b21089dfa8bca5588cd2bb24362774b4b6f2cb0"
      org.opencontainers.image.revision: "8b21089dfa8bca5588cd2bb24362774b4b6f2cb0"
      org.opencontainers.image.source: "https://github.com/linuxserver/docker-ombi"
      org.opencontainers.image.title: "Ombi"
      org.opencontainers.image.url: "https://github.com/linuxserver/docker-ombi/packages"
      org.opencontainers.image.vendor: "linuxserver.io"
      org.opencontainers.image.version: "v4.0.1468-ls108"

    logging:
      driver: "json-file"
      options: {}

    mac_address: "d2:a2:ec:81:ed:ee"

    network_mode: "bridge"

    ports:
      - "3579:3579/tcp"

    restart: "unless-stopped"

    volumes:
      - "ombi_config:/config"

    working_dir: "/"

  organizr:

    cap_drop:
      - "AUDIT_CONTROL"
      - "BLOCK_SUSPEND"
      - "DAC_READ_SEARCH"
      - "IPC_LOCK"
      - "IPC_OWNER"
      - "LEASE"
      - "LINUX_IMMUTABLE"
      - "MAC_ADMIN"
      - "MAC_OVERRIDE"
      - "NET_ADMIN"
      - "NET_BROADCAST"
      - "SYSLOG"
      - "SYS_ADMIN"
      - "SYS_BOOT"
      - "SYS_MODULE"
      - "SYS_NICE"
      - "SYS_PACCT"
      - "SYS_PTRACE"
      - "SYS_RAWIO"
      - "SYS_RESOURCE"
      - "SYS_TIME"
      - "SYS_TTY_CONFIG"
      - "WAKE_ALARM"

    container_name: "organizr"

    entrypoint:
      - "/init"

    environment:
      - "branch=v2-master"
      - "fpm=false"
      - "HOME=/root"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "PGID=1001"
      - "PS1=$$(whoami)@$$(hostname):$$(pwd)$$"
      - "PUID=1001"
      - "S6_ARCH=amd64"
      - "S6_BEHAVIOUR_IF_STAGE2_FAILS=2"
      - "S6_REL=2.2.0.3"
      - "TERM=xterm"
      - "TZ=Etc/UTC"

    hostname: "ce9e569517b9"

    image: "organizr/organizr:latest"

    ipc: "private"

    labels:
      base.maintainer: "christronyxyocum,Roxedus"
      base.s6.arch: "amd64"
      base.s6.rel: "2.2.0.3"
      maintainer: "christronyxyocum,Roxedus"
      org.label-schema.description: "Baseimage for Organizr"
      org.label-schema.name: "organizr/base"
      org.label-schema.schema-version: "1.0"
      org.label-schema.url: "https://organizr.app/"
      org.label-schema.vcs-url: "https://github.com/organizr/docker-base"
      org.opencontainers.image.created: "2021-08-20_20"
      org.opencontainers.image.source: "https://github.com/Organizr/docker-organizr/tree/master"
      org.opencontainers.image.title: "organizr/base"
      org.opencontainers.image.url: "https://github.com/Organizr/docker-organizr/blob/master/README.md"

    logging:
      driver: "json-file"
      options: {}

    network_mode: "host"

    ports:
      - "80:80/tcp"

    restart: "unless-stopped"

    volumes:
      - "organizr_config:/config"

  plex:

    cap_drop:
      - "AUDIT_CONTROL"
      - "BLOCK_SUSPEND"
      - "DAC_READ_SEARCH"
      - "IPC_LOCK"
      - "IPC_OWNER"
      - "LEASE"
      - "LINUX_IMMUTABLE"
      - "MAC_ADMIN"
      - "MAC_OVERRIDE"
      - "NET_ADMIN"
      - "NET_BROADCAST"
      - "SYSLOG"
      - "SYS_ADMIN"
      - "SYS_BOOT"
      - "SYS_MODULE"
      - "SYS_NICE"
      - "SYS_PACCT"
      - "SYS_PTRACE"
      - "SYS_RAWIO"
      - "SYS_RESOURCE"
      - "SYS_TIME"
      - "SYS_TTY_CONFIG"
      - "WAKE_ALARM"

    container_name: "plex"

    entrypoint:
      - "/init"

    environment:
      - "NVIDIA_DRIVER_CAPABILITIES=compute,video,utility"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "PGID=1000"
      - "PLEX_CLAIM=${PLEX_CLAIM_TOKEN}"
      - "PUID=1000"
      - "VERSION=docker"
      - "HOME=/root"
      - "LANGUAGE=en_US.UTF-8"
      - "LANG=en_US.UTF-8"
      - "TERM=xterm"
      - "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0"
      - "S6_VERBOSITY=1"
      - "S6_STAGE2_HOOK=/docker-mods"
      - "VIRTUAL_ENV=/lsiopy"
      - "LSIO_FIRST_PARTY=true"
      - "DEBIAN_FRONTEND=noninteractive"
      - "PLEX_DOWNLOAD=https://downloads.plex.tv/plex-media-server-new"
      - "PLEX_ARCH=amd64"
      - "PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR=/config/Library/Application Support"
      - "PLEX_MEDIA_SERVER_HOME=/usr/lib/plexmediaserver"
      - "PLEX_MEDIA_SERVER_MAX_PLUGIN_PROCS=6"
      - "PLEX_MEDIA_SERVER_USER=abc"
      - "PLEX_MEDIA_SERVER_INFO_VENDOR=Docker"
      - "PLEX_MEDIA_SERVER_INFO_DEVICE=Docker Container (LinuxServer.io)"
      - "TMPDIR=/run/plex-temp"

    hostname: "serenity"

    image: "ghcr.io/linuxserver/plex:latest"

    ipc: "private"

    labels:
      build_version: "Linuxserver.io version:- 1.24.3.5033-757abe6b4-ls76 Build-date:- 2021-09-28T05:58:19+02:00"
      maintainer: "thelamer"
      org.opencontainers.image.authors: "linuxserver.io"
      org.opencontainers.image.created: "2021-09-28T05:58:19+02:00"
      org.opencontainers.image.description: "[Plex](https://plex.tv) organizes video, music and photos\
        \ from personal media libraries and streams them to smart TVs, streaming boxes and mobile devices.\
        \ This container is packaged as a standalone Plex Media Server. has always been a top priority.\
        \ Straightforward design and bulk actions mean getting things done faster."
      org.opencontainers.image.documentation: "https://docs.linuxserver.io/images/docker-plex"
      org.opencontainers.image.licenses: "GPL-3.0-only"
      org.opencontainers.image.ref.name: "7f6e08ef13287e8ba33009e9ec473c6e86917a3c"
      org.opencontainers.image.revision: "7f6e08ef13287e8ba33009e9ec473c6e86917a3c"
      org.opencontainers.image.source: "https://github.com/linuxserver/docker-plex"
      org.opencontainers.image.title: "Plex"
      org.opencontainers.image.url: "https://github.com/linuxserver/docker-plex/packages"
      org.opencontainers.image.vendor: "linuxserver.io"
      org.opencontainers.image.version: "1.24.3.5033-757abe6b4-ls76"
      traefik.http.routers.plex.rule: "Host(`plex.nova`)"

    logging:
      driver: "json-file"
      options: {}

    network_mode: "host"

    ports:
      - "32800:32800/tcp"

    restart: "unless-stopped"

    volumes:
      - "/data1/plex_config/plex_config/_data:/config"
      - "/data1/plex_data_1/_data:/library1"
      - "/data2:/library2"
      - "/data3/movies:/library3/movies"
      - "/data3/tv:/library3/tv"

    working_dir: "/"

  portainer:

    container_name: "portainer"

    entrypoint:
      - "/portainer"

    environment:
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

    hostname: "1bc9e6af38ae"

    image: "portainer/portainer-ce:latest"

    ipc: "private"

    labels:
      com.docker.desktop.extension.api.version: ">= 0.2.2"
      com.docker.desktop.extension.icon: "https://portainer-io-assets.sfo2.cdn.digitaloceanspaces.com/logos/portainer.png"
      com.docker.extension.additional-urls: "[{\"title\":\"Website\",\"url\":\"https://www.portainer.io?utm_campaign=DockerCon&utm_source=DockerDesktop\"\
        },{\"title\":\"Documentation\",\"url\":\"https://docs.portainer.io\"},{\"title\":\"Support\",\"\
        url\":\"https://join.slack.com/t/portainer/shared_invite/zt-txh3ljab-52QHTyjCqbe5RibC2lcjKA\"\
        }]"
      com.docker.extension.detailed-description: "<p data-renderer-start-pos=\"226\">Portainer&rsquo;s\
        \ Docker Desktop extension gives you access to all of Portainer&rsquo;s rich management functionality\
        \ within your docker desktop experience.</p><h2 data-renderer-start-pos=\"374\">With Portainer\
        \ you can:</h2><ul><li>See all your running containers</li><li>Easily view all of your container\
        \ logs</li><li>Console into containers</li><li>Easily deploy your code into containers using a\
        \ simple form</li><li>Turn your YAML into custom templates for easy reuse</li></ul><h2 data-renderer-start-pos=\"\
        660\">About Portainer&nbsp;</h2><p data-renderer-start-pos=\"680\">Portainer is the worlds&rsquo;\
        \ most popular universal container management platform with more than 650,000 active monthly users.\
        \ Portainer can be used to manage Docker Standalone, Kubernetes and Docker Swarm environments\
        \ through a single common interface. It includes a simple GitOps automation engine and a Kube\
        \ API.&nbsp;</p><p data-renderer-start-pos=\"1006\">Portainer Business Edition is our fully supported\
        \ commercial grade product for business-wide use. It includes all the functionality that businesses\
        \ need to manage containers at scale. Visit <a class=\"sc-jKJlTe dPfAtb\" href=\"http://portainer.io/\"\
        \ title=\"http://Portainer.io\" data-renderer-mark=\"true\">Portainer.io</a> to learn more about\
        \ Portainer Business and <a class=\"sc-jKJlTe dPfAtb\" href=\"http://portainer.io/take-3?utm_campaign=DockerCon&amp;utm_source=Docker%20Desktop\"\
        \ title=\"http://portainer.io/take-3?utm_campaign=DockerCon&amp;utm_source=Docker%20Desktop\"\
        \ data-renderer-mark=\"true\">get 3 free nodes.</a></p>"
      com.docker.extension.publisher-url: "https://www.portainer.io"
      com.docker.extension.screenshots: "[{\"alt\": \"screenshot one\", \"url\": \"https://portainer-io-assets.sfo2.digitaloceanspaces.com/screenshots/docker-extension-1.png\"\
        },{\"alt\": \"screenshot two\", \"url\": \"https://portainer-io-assets.sfo2.digitaloceanspaces.com/screenshots/docker-extension-2.png\"\
        },{\"alt\": \"screenshot three\", \"url\": \"https://portainer-io-assets.sfo2.digitaloceanspaces.com/screenshots/docker-extension-3.png\"\
        },{\"alt\": \"screenshot four\", \"url\": \"https://portainer-io-assets.sfo2.digitaloceanspaces.com/screenshots/docker-extension-4.png\"\
        },{\"alt\": \"screenshot five\", \"url\": \"https://portainer-io-assets.sfo2.digitaloceanspaces.com/screenshots/docker-extension-5.png\"\
        },{\"alt\": \"screenshot six\", \"url\": \"https://portainer-io-assets.sfo2.digitaloceanspaces.com/screenshots/docker-extension-6.png\"\
        },{\"alt\": \"screenshot seven\", \"url\": \"https://portainer-io-assets.sfo2.digitaloceanspaces.com/screenshots/docker-extension-7.png\"\
        },{\"alt\": \"screenshot eight\", \"url\": \"https://portainer-io-assets.sfo2.digitaloceanspaces.com/screenshots/docker-extension-8.png\"\
        },{\"alt\": \"screenshot nine\", \"url\": \"https://portainer-io-assets.sfo2.digitaloceanspaces.com/screenshots/docker-extension-9.png\"\
        }]"
      io.portainer.server: "true"
      org.opencontainers.image.description: "Docker container management made simple, with the world’s\
        \ most popular GUI-based container management platform."
      org.opencontainers.image.title: "Portainer"
      org.opencontainers.image.vendor: "Portainer.io"

    logging:
      driver: "json-file"
      options: {}

    mac_address: "5e:08:8b:3d:44:fc"

    network_mode: "bridge"

    ports:
      - "9000:9000/tcp"
      - "9443:9443/tcp"

    restart: "always"

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainer_data:/data"

    working_dir: "/"

  prowlarr:

    cap_drop:
      - "AUDIT_CONTROL"
      - "BLOCK_SUSPEND"
      - "DAC_READ_SEARCH"
      - "IPC_LOCK"
      - "IPC_OWNER"
      - "LEASE"
      - "LINUX_IMMUTABLE"
      - "MAC_ADMIN"
      - "MAC_OVERRIDE"
      - "NET_ADMIN"
      - "NET_BROADCAST"
      - "SYSLOG"
      - "SYS_ADMIN"
      - "SYS_BOOT"
      - "SYS_MODULE"
      - "SYS_NICE"
      - "SYS_PACCT"
      - "SYS_PTRACE"
      - "SYS_RAWIO"
      - "SYS_RESOURCE"
      - "SYS_TIME"
      - "SYS_TTY_CONFIG"
      - "WAKE_ALARM"

    container_name: "prowlarr"

    entrypoint:
      - "/init"

    environment:
      - "TZ=Etc/UTC"
      - "PUID=1000"
      - "PGID=1000"
      - "PATH=/lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "PS1=$$(whoami)@$$(hostname):$$(pwd)\\$$"
      - "HOME=/root"
      - "TERM=xterm"
      - "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0"
      - "S6_VERBOSITY=1"
      - "S6_STAGE2_HOOK=/docker-mods"
      - "VIRTUAL_ENV=/lsiopy"
      - "LSIO_FIRST_PARTY=true"
      - "XDG_CONFIG_HOME=/config/xdg"
      - "COMPlus_EnableDiagnostics=0"
      - "TMPDIR=/run/prowlarr-temp"

    hostname: "1d08e4948609"

    image: "lscr.io/linuxserver/prowlarr:latest"

    ipc: "private"

    labels:
      build_version: "Linuxserver.io version:- 2.3.0.5236-ls136 Build-date:- 2026-02-04T05:01:26+00:00"
      com.docker.compose.config-hash: "ce0eef9d01f896d1eb02df934bd5a9184c04768edef18d2bfed5aab3e1d60a0e"
      com.docker.compose.container-number: "1"
      com.docker.compose.depends_on: ""
      com.docker.compose.image: "sha256:0896dd6c8b696d781d6e99c4117b4545eccd9b1ecd6c1304903a22838b3e73b1"
      com.docker.compose.oneoff: "False"
      com.docker.compose.project: "prowlarr"
      com.docker.compose.project.config_files: "/home/koonan/prowlarr/docker-compose.yaml"
      com.docker.compose.project.working_dir: "/home/koonan/prowlarr"
      com.docker.compose.service: "prowlarr"
      com.docker.compose.version: "2.35.1"
      maintainer: "Roxedus,thespad"
      org.opencontainers.image.authors: "linuxserver.io"
      org.opencontainers.image.created: "2026-02-04T05:01:26+00:00"
      org.opencontainers.image.description: "[Prowlarr](https://github.com/Prowlarr/Prowlarr) is a indexer\
        \ manager/proxy built on the popular arr .net/reactjs base stack to integrate with your various\
        \ PVR apps. Prowlarr supports both Torrent Trackers and Usenet Indexers. It integrates seamlessly\
        \ with Sonarr, Radarr, Lidarr, and Readarr offering complete management of your indexers with\
        \ no per app Indexer setup required (we do it all).  "
      org.opencontainers.image.documentation: "https://docs.linuxserver.io/images/docker-prowlarr"
      org.opencontainers.image.licenses: "GPL-3.0-only"
      org.opencontainers.image.ref.name: "c69d919784c79f1b91f0a33d7869e0e3746f404b"
      org.opencontainers.image.revision: "c69d919784c79f1b91f0a33d7869e0e3746f404b"
      org.opencontainers.image.source: "https://github.com/linuxserver/docker-prowlarr"
      org.opencontainers.image.title: "Prowlarr"
      org.opencontainers.image.url: "https://github.com/linuxserver/docker-prowlarr/packages"
      org.opencontainers.image.vendor: "linuxserver.io"
      org.opencontainers.image.version: "2.3.0.5236-ls136"

    logging:
      driver: "json-file"
      options: {}

    mac_address: "e6:35:6b:a7:1b:ad"

    networks:
      - "media"

    ports:
      - "9696:9696/tcp"

    restart: "unless-stopped"

    volumes:
      - "/path/to/prowlarr/data:/config"

    working_dir: "/"

  radarr:

    cap_drop:
      - "AUDIT_CONTROL"
      - "BLOCK_SUSPEND"
      - "DAC_READ_SEARCH"
      - "IPC_LOCK"
      - "IPC_OWNER"
      - "LEASE"
      - "LINUX_IMMUTABLE"
      - "MAC_ADMIN"
      - "MAC_OVERRIDE"
      - "NET_ADMIN"
      - "NET_BROADCAST"
      - "SYSLOG"
      - "SYS_ADMIN"
      - "SYS_BOOT"
      - "SYS_MODULE"
      - "SYS_NICE"
      - "SYS_PACCT"
      - "SYS_PTRACE"
      - "SYS_RAWIO"
      - "SYS_RESOURCE"
      - "SYS_TIME"
      - "SYS_TTY_CONFIG"
      - "WAKE_ALARM"

    container_name: "radarr"

    entrypoint:
      - "/init"

    environment:
      - "LANG=en_US.UTF-8"
      - "LANGUAGE=en_US.UTF-8"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "PGID=1000"
      - "PS1=$$(whoami)@$$(hostname):$$(pwd)\\$$"
      - "PUID=1000"
      - "TZ=America/Chicago"
      - "HOME=/root"
      - "TERM=xterm"
      - "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0"
      - "S6_VERBOSITY=1"
      - "S6_STAGE2_HOOK=/docker-mods"
      - "VIRTUAL_ENV=/lsiopy"
      - "LSIO_FIRST_PARTY=true"
      - "XDG_CONFIG_HOME=/config/xdg"
      - "COMPlus_EnableDiagnostics=0"
      - "TMPDIR=/run/radarr-temp"

    hostname: "155d40782f42"

    image: "ghcr.io/linuxserver/radarr:latest"

    ipc: "private"

    labels:
      build_version: "Linuxserver.io version:- 3.2.2.5080-ls117 Build-date:- 2021-09-27T17:58:47+02:00"
      maintainer: "thelamer"
      org.opencontainers.image.authors: "linuxserver.io"
      org.opencontainers.image.created: "2021-09-27T17:58:47+02:00"
      org.opencontainers.image.description: "[Radarr](https://github.com/Radarr/Radarr) - A fork of Sonarr\
        \ to work with movies à la Couchpotato.  "
      org.opencontainers.image.documentation: "https://docs.linuxserver.io/images/docker-radarr"
      org.opencontainers.image.licenses: "GPL-3.0-only"
      org.opencontainers.image.ref.name: "3d3be90eb1f3277c6fd53e3dee434052f08bd0dc"
      org.opencontainers.image.revision: "3d3be90eb1f3277c6fd53e3dee434052f08bd0dc"
      org.opencontainers.image.source: "https://github.com/linuxserver/docker-radarr"
      org.opencontainers.image.title: "Radarr"
      org.opencontainers.image.url: "https://github.com/linuxserver/docker-radarr/packages"
      org.opencontainers.image.vendor: "linuxserver.io"
      org.opencontainers.image.version: "3.2.2.5080-ls117"
      traefik.enable: "true"
      traefik.http.routers.radarr.entrypoints: "web"
      traefik.http.routers.radarr.rule: "Host(`/radarr`)"
      traefik.http.services.radarr.loadbalancer.server.port: "7878"

    logging:
      driver: "json-file"
      options: {}

    networks:
      - "media"

    ports:
      - "7878:7878/tcp"

    restart: "unless-stopped"

    volumes:
      - "/data1/plex_data_1/_data/movies:/plex_movies_1"
      - "/data2/movies:/plex_movies_2"
      - "/data3/movies:/plex_movies_3"
      - "radarr_config:/config"
      - "transmission_data:/data"

    working_dir: "/"

  sonarr:

    cap_drop:
      - "CAP_AUDIT_CONTROL"
      - "CAP_BLOCK_SUSPEND"
      - "CAP_DAC_READ_SEARCH"
      - "CAP_IPC_LOCK"
      - "CAP_IPC_OWNER"
      - "CAP_LEASE"
      - "CAP_LINUX_IMMUTABLE"
      - "CAP_MAC_ADMIN"
      - "CAP_MAC_OVERRIDE"
      - "CAP_NET_ADMIN"
      - "CAP_NET_BROADCAST"
      - "CAP_SYSLOG"
      - "CAP_SYS_ADMIN"
      - "CAP_SYS_BOOT"
      - "CAP_SYS_MODULE"
      - "CAP_SYS_NICE"
      - "CAP_SYS_PACCT"
      - "CAP_SYS_PTRACE"
      - "CAP_SYS_RAWIO"
      - "CAP_SYS_RESOURCE"
      - "CAP_SYS_TIME"
      - "CAP_SYS_TTY_CONFIG"
      - "CAP_WAKE_ALARM"

    container_name: "sonarr"

    entrypoint:
      - "/init"

    environment:
      - "PGID=1000"
      - "PUID=1000"
      - "TZ=America/Chicago"
      - "PATH=/lsiopy/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "PS1=$$(whoami)@$$(hostname):$$(pwd)\\$$ "
      - "HOME=/root"
      - "TERM=xterm"
      - "S6_CMD_WAIT_FOR_SERVICES_MAXTIME=0"
      - "S6_VERBOSITY=1"
      - "S6_STAGE2_HOOK=/docker-mods"
      - "VIRTUAL_ENV=/lsiopy"
      - "LSIO_FIRST_PARTY=true"
      - "XDG_CONFIG_HOME=/config/xdg"
      - "SONARR_CHANNEL=v4-stable"
      - "SONARR_BRANCH=main"
      - "COMPlus_EnableDiagnostics=0"
      - "TMPDIR=/run/sonarr-temp"

    hostname: "21cab3d173e2"

    image: "ghcr.io/linuxserver/sonarr:latest"

    ipc: "private"

    labels:
      build_version: "Linuxserver.io version:- 3.0.6.1342-ls124 Build-date:- 2021-10-01T00:32:18+02:00"
      maintainer: "thespad"
      org.opencontainers.image.authors: "linuxserver.io"
      org.opencontainers.image.created: "2021-10-01T00:32:18+02:00"
      org.opencontainers.image.description: "[Sonarr](https://sonarr.tv/) (formerly NZBdrone) is a PVR\
        \ for usenet and bittorrent users. It can monitor multiple RSS feeds for new episodes of your\
        \ favorite shows and will grab, sort and rename them. It can also be configured to automatically\
        \ upgrade the quality of files already downloaded when a better quality format becomes available.\
        \  "
      org.opencontainers.image.documentation: "https://docs.linuxserver.io/images/docker-sonarr"
      org.opencontainers.image.licenses: "GPL-3.0-only"
      org.opencontainers.image.ref.name: "3c26433c5a0bce74a278dae904eec769077aeb6f"
      org.opencontainers.image.revision: "3c26433c5a0bce74a278dae904eec769077aeb6f"
      org.opencontainers.image.source: "https://github.com/linuxserver/docker-sonarr"
      org.opencontainers.image.title: "Sonarr"
      org.opencontainers.image.url: "https://github.com/linuxserver/docker-sonarr/packages"
      org.opencontainers.image.vendor: "linuxserver.io"
      org.opencontainers.image.version: "3.0.6.1342-ls124"

    logging:
      driver: "json-file"
      options: {}

    networks:
      - "media"

    ports:
      - "8989:8989/tcp"

    restart: "unless-stopped"

    volumes:
      - "/data1/plex_data_1/_data/tv:/plex_tv_1"
      - "/data2/tv:/plex_tv_2"
      - "/data3/tv:/plex_tv_3"
      - "sonarr_config:/config"
      - "transmission_data:/data"

    working_dir: "/"

  tautulli:

    command:
      - "python"
      - "Tautulli.py"
      - "--datadir"
      - "/config"

    container_name: "tautulli"

    entrypoint:
      - "./start.sh"

    environment:
      - "PGID=1000"
      - "TZ=America/Chicago"
      - "PUID=1000"
      - "GPG_KEY=E3FF2839C048B25C084DEBE9B26995E310250568"
      - "PYTHON_VERSION=3.9.16"
      - "PYTHON_PIP_VERSION=22.0.4"
      - "PYTHON_SETUPTOOLS_VERSION=58.1.0"
      - "PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/d5cb0afaf23b8520f1bbcfed521017b4a95f5c01/public/get-pip.py"
      - "PYTHON_GET_PIP_SHA256=394be00f13fa1b9aaa47e911bdb59a09c3b2986472130f30aa0bfaf7f3980637"
      - "PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "LANG=C.UTF-8"
      - "PYTHON_SHA256=2a9920c7a0cd236de33644ed980a13cbbc21058bfdc528febb6081575ed73be3"
      - "TAUTULLI_DOCKER=True"

    hostname: "97f2eff809c1"

    image: "ghcr.io/tautulli/tautulli:latest"

    ipc: "private"

    labels:
      maintainer: "Tautulli"
      org.opencontainers.image.created: "2025-09-09T00:57:49.263Z"
      org.opencontainers.image.description: "A Python based monitoring and tracking tool for Plex Media\
        \ Server."
      org.opencontainers.image.licenses: "GPL-3.0"
      org.opencontainers.image.revision: "cc0150a1b2b745980467003a73aa1be51c1e426a"
      org.opencontainers.image.source: "https://github.com/Tautulli/Tautulli"
      org.opencontainers.image.title: "Tautulli"
      org.opencontainers.image.url: "https://github.com/Tautulli/Tautulli"
      org.opencontainers.image.version: "master"

    logging:
      driver: "json-file"
      options: {}

    mac_address: "e2:ef:0d:7f:e9:17"

    network_mode: "bridge"

    ports:
      - "8181:8181/tcp"

    restart: "unless-stopped"

    volumes:
      - "tautulli_config:/config"

    working_dir: "/app"

  test:
    command:
      - "nginx"
      - "-g"
      - "daemon off;"
    container_name: "test"
    entrypoint:
      - "/docker-entrypoint.sh"
    environment:
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "NGINX_VERSION=1.29.4"
      - "PKG_RELEASE=1"
      - "DYNPKG_RELEASE=1"
      - "NJS_VERSION=0.9.4"
      - "NJS_RELEASE=1"
      - "ACME_VERSION=0.3.1"
    hostname: "e4be072722e2"
    image: "movienight:test"
    ipc: "private"
    labels:
      maintainer: "NGINX Docker Maintainers <docker-maint@nginx.com>"
    logging:
      driver: "json-file"
      options: {}
    network_mode: "bridge"
    ports:
      - "9000:80/tcp"
    working_dir: "/"

  traefik-traefik-1:

    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"

    container_name: "traefik-traefik-1"

    entrypoint:
      - "/entrypoint.sh"

    environment:
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

    hostname: "791e5a959ea1"

    image: "traefik:v3.6"

    ipc: "private"

    labels:
      com.docker.compose.config-hash: "94ad8ca976eec0cb23c03c7b973ae6cdc2599586e79d35bedde667ebc2001b0e"
      com.docker.compose.container-number: "1"
      com.docker.compose.depends_on: ""
      com.docker.compose.image: "sha256:f174a52e1993a764172bba2c07106a766f2895b2b069a19c7d3bb6f69a18d222"
      com.docker.compose.oneoff: "False"
      com.docker.compose.project: "traefik"
      com.docker.compose.project.config_files: "/opt/stacks/traefik/compose.yaml"
      com.docker.compose.project.working_dir: "/opt/stacks/traefik"
      com.docker.compose.replace: "40753551fcf2b0164ffacd98af763fd3022ef332546fd3442aaf4204807c045f"
      com.docker.compose.service: "traefik"
      com.docker.compose.version: "2.34.0"
      org.opencontainers.image.description: "A modern reverse-proxy"
      org.opencontainers.image.documentation: "https://docs.traefik.io"
      org.opencontainers.image.source: "https://github.com/traefik/traefik"
      org.opencontainers.image.title: "Traefik"
      org.opencontainers.image.url: "https://traefik.io"
      org.opencontainers.image.vendor: "Traefik Labs"
      org.opencontainers.image.version: "v3.6.6"

    logging:
      driver: "json-file"
      options: {}

    networks:
      - "traefik_default"

    ports:
      - "80:80/tcp"
      - "8080:8080/tcp"

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

    working_dir: "/"

  transmission:

    cap_drop:
      - "AUDIT_CONTROL"
      - "BLOCK_SUSPEND"
      - "DAC_READ_SEARCH"
      - "IPC_LOCK"
      - "IPC_OWNER"
      - "LEASE"
      - "LINUX_IMMUTABLE"
      - "MAC_ADMIN"
      - "MAC_OVERRIDE"
      - "NET_BROADCAST"
      - "SYSLOG"
      - "SYS_ADMIN"
      - "SYS_BOOT"
      - "SYS_MODULE"
      - "SYS_NICE"
      - "SYS_PACCT"
      - "SYS_PTRACE"
      - "SYS_RAWIO"
      - "SYS_RESOURCE"
      - "SYS_TIME"
      - "SYS_TTY_CONFIG"
      - "WAKE_ALARM"

    command:
      - "dumb-init"
      - "/etc/openvpn/start.sh"

    container_name: "transmission"

    environment:
      - "CREATE_TUN_DEVICE=true"
      - "DROP_DEFAULT_ROUTE="
      - "ENABLE_UFW=false"
      - "GLOBAL_APPLY_PERMISSIONS=true"
      - "HEALTH_CHECK_HOST=google.com"
      - "LOCAL_NETWORK=10.0.0.0/16"
      - "LOG_TO_STDOUT=false"
      - "OPENVPN_CONFIG=se_all"
      - "OPENVPN_PASSWORD=${TRANSMISSION_OPENVPN_PASSWORD}"
      - "OPENVPN_PROVIDER=MULLVAD"
      - "OPENVPN_USERNAME=${TRANSMISSION_OPENVPN_USERNAME}"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "PEER_DNS=true"
      - "PEER_DNS_PIN_ROUTES=true"
      - "PGID=1000"
      - "PUID=1000"
      - "REVISION=ae45b1f22178ddee089d9ea10d4732dbde2d8ef2"
      - "SELFHEAL=false"
      - "TRANSMISSION_DOWNLOAD_DIR=/data/completed"
      - "TRANSMISSION_HOME=/data/transmission-home"
      - "TRANSMISSION_INCOMPLETE_DIR=/data/incomplete"
      - "TRANSMISSION_RPC_PORT=9091"
      - "TRANSMISSION_WATCH_DIR=/data/watch"
      - "UFW_ALLOW_GW_NET=false"
      - "UFW_DISABLE_IPTABLES_REJECT=false"
      - "UFW_EXTRA_PORTS="
      - "WEBPROXY_ENABLED=false"
      - "WEBPROXY_PASSWORD=${TRANSMISSION_WEBPROXY_PASSWORD:-}"
      - "WEBPROXY_PORT=8118"
      - "WEBPROXY_USERNAME=${TRANSMISSION_WEBPROXY_USERNAME:-}"
      - "TRANSMISSION_RPC_USERNAME=${TRANSMISSION_RPC_USERNAME:-}"
      - "TRANSMISSION_RPC_PASSWORD=${TRANSMISSION_RPC_PASSWORD:-}"
      - "OPENVPN_OPTS="
      - "WEBPROXY_BIND_ADDRESS="

    hostname: "bf9d2a3af845"

    image: "haugene/transmission-openvpn:dev"

    ipc: "private"

    labels:
      autoheal: "true"
      org.opencontainers.image.created: "2025-05-28T19:05:34.665Z"
      org.opencontainers.image.description: "Docker container running Transmission torrent client with\
        \ WebUI over an OpenVPN tunnel"
      org.opencontainers.image.licenses: "GPL-3.0"
      org.opencontainers.image.ref.name: "ubuntu"
      org.opencontainers.image.revision: "ae45b1f22178ddee089d9ea10d4732dbde2d8ef2"
      org.opencontainers.image.source: "https://github.com/haugene/docker-transmission-openvpn"
      org.opencontainers.image.title: "docker-transmission-openvpn"
      org.opencontainers.image.url: "https://github.com/haugene/docker-transmission-openvpn"
      org.opencontainers.image.version: "dev"

    logging:
      driver: "json-file"
      options:
        max-size: "10m"

    networks:
      - "media"

    ports:
      - "9094:9091/tcp"

    restart: "unless-stopped"

    volumes:
      - "transmission_config:/config"
      - "transmission_data:/data"

  vibe-kanban:

    cap_drop:
      - "AUDIT_CONTROL"
      - "BLOCK_SUSPEND"
      - "DAC_READ_SEARCH"
      - "IPC_LOCK"
      - "IPC_OWNER"
      - "LEASE"
      - "LINUX_IMMUTABLE"
      - "MAC_ADMIN"
      - "MAC_OVERRIDE"
      - "NET_ADMIN"
      - "NET_BROADCAST"
      - "SYSLOG"
      - "SYS_ADMIN"
      - "SYS_BOOT"
      - "SYS_MODULE"
      - "SYS_NICE"
      - "SYS_PACCT"
      - "SYS_PTRACE"
      - "SYS_RAWIO"
      - "SYS_RESOURCE"
      - "SYS_TIME"
      - "SYS_TTY_CONFIG"
      - "WAKE_ALARM"

    command:
      - "npx"
      - "vibe-kanban"

    container_name: "vibe-kanban"

    entrypoint:
      - "docker-entrypoint.sh"

    environment:
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "NODE_VERSION=20.20.0"
      - "YARN_VERSION=1.22.22"
      - "PORT=3000"

    hostname: "nova"

    image: "vibe-kanban:latest"

    ipc: "private"

    logging:
      driver: "json-file"
      options: {}

    network_mode: "host"

    ports:
      - "2468:3000/tcp"

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "vibe-kanban-repos:/repos"

    working_dir: "/app"

  volume-sharer:
    container_name: "volume-sharer"
    entrypoint:
      - "volume-sharer.sh"
    environment:
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "USERID=0"
      - "GROUPID=0"
    hostname: "serenity"
    image: "gdiepen/volume-sharer"
    ipc: "private"
    logging:
      driver: "json-file"
      options: {}
    network_mode: "host"
    ports:
      - "139:139/tcp"
      - "445:445/tcp"
    restart: "unless-stopped"
    volumes:
      - "/var/lib/docker/volumes:/docker_volumes"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "d38249258c4c2870a526afa1ff60410a6ef5c618649a43f795388a9cd0d69b12:/etc/samba"

  wud:
    command:
      - "node"
      - "index"
    container_name: "wud"
    entrypoint:
      - "/usr/bin/entrypoint.sh"
    environment:
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "NODE_VERSION=23.11.1"
      - "YARN_VERSION=1.22.22"
      - "WORKDIR=/home/node/app"
      - "WUD_LOG_FORMAT=text"
      - "WUD_VERSION=8.1.1"
    hostname: "3c1f06c61711"
    image: "getwud/wud"
    ipc: "private"
    labels:
      com.docker.compose.config-hash: "18b44e4b81de65d265b1f1107242b63c2d890399fabf79a4ce3dab9ed77540ee"
      com.docker.compose.container-number: "1"
      com.docker.compose.depends_on: ""
      com.docker.compose.image: "sha256:f39367c3ffad9a03cb2f540138902194de0f0b15a2cf9ab992ef6f0e908b94ea"
      com.docker.compose.oneoff: "False"
      com.docker.compose.project: "wud"
      com.docker.compose.project.config_files: "/opt/stacks/wud/compose.yaml"
      com.docker.compose.project.working_dir: "/opt/stacks/wud"
      com.docker.compose.service: "whatsupdocker"
      com.docker.compose.version: "2.34.0"
      maintainer: "fmartinou"
    logging:
      driver: "json-file"
      options: {}
    networks:
      - "wud_default"
    ports:
      - "3003:3000/tcp"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    working_dir: "/home/node/app"

  zwave-js-ui:

    command:
      - "node"
      - "server/bin/www"

    container_name: "zwave-js-ui"

    devices:
      - "/dev/serial/by-id/usb-Zooz_800_Z-Wave_Stick_533D004242-if00:/dev/zwave"

    environment:
      - "ZWAVEJS_EXTERNAL_CONFIG=/usr/src/app/store/.config-db"
      - "TZ=America/Chicago"
      - "SESSION_SECRET=${ZWAVE_SESSION_SECRET}"
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "TAG_NAME="
      - "NODE_ENV=production"

    hostname: "dfc2d38d29a3"

    image: "zwavejs/zwave-js-ui:latest"

    ipc: "private"

    labels:
      com.docker.compose.config-hash: "8b32164dc70e2cd42b7f1bb9de09b010306923a7acac6a866e46621a8bf001e3"
      com.docker.compose.container-number: "1"
      com.docker.compose.depends_on: ""
      com.docker.compose.image: "sha256:a5f36f9f363c1d45e70c3d779a70045d379781807dafe3c730df5ef45d270dea"
      com.docker.compose.oneoff: "False"
      com.docker.compose.project: "zwave"
      com.docker.compose.project.config_files: "/opt/stacks/zwave/compose.yaml"
      com.docker.compose.project.working_dir: "/opt/stacks/zwave"
      com.docker.compose.service: "zwave-js-ui"
      com.docker.compose.version: "2.34.0"
      maintainer: "robertsLando"
      org.opencontainers.image.authors: "Daniel Lando <daniel.sorridi@gmail.com>"
      org.opencontainers.image.created: "2025-10-29T16:51:49.611Z"
      org.opencontainers.image.description: "Full featured Z-Wave Control Panel UI and MQTT gateway. Built\
        \ using Nodejs, and Vue/Vuetify"
      org.opencontainers.image.documentation: "https://zwave-js.github.io/zwave-js-ui"
      org.opencontainers.image.licenses: "MIT"
      org.opencontainers.image.revision: "44b16b2d3de4841ff6b3f29dcc15cd6e6931d6bd"
      org.opencontainers.image.source: "https://github.com/zwave-js/zwave-js-ui"
      org.opencontainers.image.title: "zwave-js-ui"
      org.opencontainers.image.url: "https://github.com/zwave-js/zwave-js-ui"
      org.opencontainers.image.vendor: "zwave-js"
      org.opencontainers.image.version: "11.6.1"

    logging:
      driver: "json-file"
      options: {}

    networks:
      - "zwave_zwave"

    ports:
      - "3002:3000/tcp"
      - "8091:8091/tcp"

    restart: "always"

    tty: true

    volumes:
      - "zwave-js-ui:/usr/src/app/store"

    working_dir: "/usr/src/app"

version: "3.6"

volumes:

  backrest_backrest_cache:
    external: true

  backrest_backrest_config:
    external: true

  backrest_backrest_data:
    external: true

  bazarr_config:
    external: true

  d38249258c4c2870a526afa1ff60410a6ef5c618649a43f795388a9cd0d69b12:
    external: true

  eeba826780300f3d846b69ccaecc2f70dc9dd09cdb8ce35b3eb4462d5ee3b122:
    external: true

  ha_config:
    external: true

  immich_immich-ml-model-cache:
    external: true

  jackett_config:
    external: true

  jackett_download:
    external: true

  minecraft_data:
    external: true

  ombi_config:
    external: true

  organizr_config:
    external: true

  portainer_data:
    external: true

  radarr_config:
    external: true

  sonarr_config:
    external: true

  tautulli_config:
    external: true

  transmission_config:
    external: true

  transmission_data:
    external: true

  vibe-kanban-repos:
    external: true

  zwave-js-ui:
    external: true
