# Gaming Stack - Minecraft Server
# Usage: docker compose -f docker-compose.gaming.yaml up -d

services:

  minecraft:

    cap_drop:
      - "AUDIT_CONTROL"
      - "BLOCK_SUSPEND"
      - "DAC_READ_SEARCH"
      - "IPC_LOCK"
      - "IPC_OWNER"
      - "LEASE"
      - "LINUX_IMMUTABLE"
      - "MAC_ADMIN"
      - "MAC_OVERRIDE"
      - "NET_ADMIN"
      - "NET_BROADCAST"
      - "SYSLOG"
      - "SYS_ADMIN"
      - "SYS_BOOT"
      - "SYS_MODULE"
      - "SYS_NICE"
      - "SYS_PACCT"
      - "SYS_PTRACE"
      - "SYS_RAWIO"
      - "SYS_RESOURCE"
      - "SYS_TIME"
      - "SYS_TTY_CONFIG"
      - "WAKE_ALARM"

    container_name: "minecraft"

    entrypoint:
      - "/start"

    environment:
      - "EULA=TRUE"
      - "PATH=/opt/java/openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - "JAVA_HOME=/opt/java/openjdk"
      - "LANG=en_US.UTF-8"
      - "LANGUAGE=en_US:en"
      - "LC_ALL=en_US.UTF-8"
      - "JAVA_VERSION=jdk-21.0.5+11"
      - "TYPE=VANILLA"
      - "VERSION=LATEST"
      - "UID=1000"
      - "GID=1000"

    hostname: "adcfacfd63e3"

    image: "itzg/minecraft-server:latest"

    ipc: "private"

    labels:
      org.opencontainers.image.authors: "Geoff Bourne <itzgeoff@gmail.com>"
      org.opencontainers.image.created: "2024-12-14T21:22:25.728Z"
      org.opencontainers.image.description: "Docker image that provides a Minecraft Server that will automatically\
        \ download selected version at startup"
      org.opencontainers.image.licenses: "Apache-2.0"
      org.opencontainers.image.ref.name: "ubuntu"
      org.opencontainers.image.revision: "de19794a5fa90a7736d7fc461c1978d70516c129"
      org.opencontainers.image.source: "https://github.com/itzg/docker-minecraft-server"
      org.opencontainers.image.title: "docker-minecraft-server"
      org.opencontainers.image.url: "https://github.com/itzg/docker-minecraft-server"
      org.opencontainers.image.version: "java21"

    logging:
      driver: "json-file"
      options: {}

    network_mode: "bridge"

    ports:
      - "25565:25565/tcp"

    stdin_open: true

    tty: true

    volumes:
      - "minecraft_data:/data"

    working_dir: "/data"

version: "3.6"

volumes:

  minecraft_data:
    external: true
