---
- System:
    - data1:
        widget:
          type: glances
          url: http://host.docker.internal:61208
          version: 4
          metric: fs:/data1
    - data2:
        widget:
          type: glances
          url: http://host.docker.internal:61208
          version: 4
          metric: fs:/data2
    - data3:
        widget:
          type: glances
          url: http://host.docker.internal:61208
          version: 4
          metric: fs:/data3
