FROM ghcr.io/kdlbs/kandev:latest

USER root

# RUN npm install -g @anthropic-ai/claude-code

COPY docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
RUN chmod +x /usr/local/bin/docker-entrypoint.sh
